config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  resources :posts do
    resources :comments, except: [:index, :show, :new]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show] do
    resources :friendships, except: [:show, :edit, :update], shallow: true
  end

  get 'users/:user_id/friendships/pending', to: 'friendships#pending', as: :pending_friendships
  post 'users/:user_id/friendships/pending', to: 'friendships#accept', as: :accept_friendship

  devise_scope :user do
    authenticated :user do
      root to: "posts#index", as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      user.avatar = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  has_one_attached :avatar, dependent: :destroy
  has_many :posts, dependent: :destroy, foreign_key: 'author'
  has_many :comments, dependent: :destroy, foreign_key: 'author'
  has_many :likes, dependent: :destroy

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :received_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :received_friends, through: :received_friendships, source: :user

  def active_friends
    friends.select{ |friend| friend.friends.include?(self) }
  end

  def pending_friends
    friends.select{ |friend| !friend.friends.include?(self) }
  end

  def pending_friendships
    friendships.select{ |friendship| !friendship.is_mutual }
  end

  def pending_received_friendships
    received_friendships.select{ |friendship| !friendship.is_mutual }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.order("created_at DESC")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-128x128">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar.variant(resize_to_fill: [128, 128, { gravity: 'Center' }]) %>
      <% else %>
        <img src="https://bulma.io/images/placeholders/128x128.png">
      <% end %>
    </p>
  </figure>

  <div class="media-content">
    <div class="content">
      <p><strong>Name:</strong> <%= @user.name %></p>
      <p><strong>Username:</strong> <%= @user.username %></p>
      <p><%= link_to "#{@user.name}'s Friends", user_friendships_path(@user) %></p>
      <hr>
      <p><strong>Posts:</strong></p>
      <ul>
        <% @posts.each do |post| %>
          <li><%= link_to post.content[0,15], post_path(post) %>, <%= distance_of_time_in_words(post.created_at, Time.now) %> ago</li>
        <% end %>
      </ul>
    </div>
  </div>
</article>

app/views/users/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <%= render 'posts/profile' %>

      <div class="column is-two-thirds">
        <div class="box">
          <h1 class="title">All Users</h1>

          <% @users.each do |user| %>
            <article class="media">
              <figure class="media-left">
                <p class="image is-48x48">
                  <% if user.avatar.attached? %>
                    <%= image_tag user.avatar.variant(resize_to_fill: [128, 128, { gravity: 'Center' }]) %>
                  <% else %>
                    <img src="https://bulma.io/images/placeholders/128x128.png">
                  <% end %>
                </p>
              </figure>

              <div class="media-content">
                <div class="content">
                  <strong><%= link_to user.name, user %></strong>, @<%= user.username %>
                </div>
              </div>

              <div class="media-right">
                <% unless current_user.active_friends.include?(user) || current_user.pending_friends.include?(user) || current_user.received_friends.include?(user) || current_user == user %>
                  <%= link_to "Add Friend", user_friendships_path(user_id: current_user.id, friendship: {friend_id: user}), method: :post, remote: true, class: "button is-link" %>
                <% end %>
              </div>
            </article>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <%= render 'posts/profile' %>

      <div class="column is-two-thirds">
        <div class="box">
          <h1 class="title"><%= @user.name %>'s Profile</h1>
          
          <%= render 'profile' %>

        </div>
      </div>
    </div>
  </div>
</section>