config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  resources :posts do
    resources :comments, except: [:index, :show, :new]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show] do
    resources :friendships, except: [:show, :edit, :update], shallow: true
  end

  get 'users/:user_id/friendships/pending', to: 'friendships#pending', as: :pending_friendships
  post 'users/:user_id/friendships/pending', to: 'friendships#accept', as: :accept_friendship

  devise_scope :user do
    authenticated :user do
      root to: "posts#index", as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates_presence_of :user_id, :friend_id
  validate :user_is_not_equal_friend
  validates_uniqueness_of :user_id, scope: [:friend_id]

  def is_mutual
    self.friend.friends.include?(self.user)
  end

  private
    def user_is_not_equal_friend
      errors.add(:friend, "can't be the same as the user") if self.user == self.friend
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize, except: [:index, :destroy]

  def index
    @user = User.find(params[:user_id])
    @friends = @user.active_friends
  end

  def pending
    @user = User.find(params[:user_id])
    @sent_requests = @user.pending_friendships
    @received_requests = @user.pending_received_friendships
  end

  def new
    @friendship = current_user.friendships.build
  end
  
  def create
    @friendship = current_user.friendships.build(friendship_params)

    if @friendship.save
      redirect_to pending_friendships_path(current_user), notice: 'Friend request sent.'
    else
      redirect_back(fallback_location: users_path, alert: 'Friend request could not be sent.')
    end
  end

  def accept
    @friendship = current_user.friendships.build(friendship_params)

    @friendship.save
    redirect_to user_friendships_path(current_user), notice: 'Friend request accepted.'
  end

  def destroy
    @friendship = Friendship.find(params[:id])

    if @friendship.is_mutual
      @friend = @friendship.friend
      @mutual_friendship = @friend.friends.find(current_user)

      @friendship.destroy
      @mutual_friendship.destroy
      flash[:alert] = "Friend deleted."
    else
      @friendship.destroy
      flash[:alert] = "Friend request deleted."
    end

    redirect_to user_friendships_path(current_user)
  end

  private
    def friendship_params
      params.require(:friendship).permit(:friend_id)
    end

    def authorize
      @user = User.find(params[:user_id])
      unless current_user == @user
        redirect_to user_friendships_path(@user), alert: 'You cannot do that.'
      end
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <%= render 'posts/profile' %>

      <div class="column is-two-thirds">
        <div class="box">
          <h1 class="title"><%= link_to @user.name, user_path(@user) %>'s Friends</h1>

          <% @friends.each do |friend| %>
            <article class="media">
              <figure class="media-left">
                <p class="image is-48x48">
                  <% if friend.avatar.attached? %>
                    <%= image_tag friend.avatar.variant(resize_to_fill: [128, 128, { gravity: 'Center' }]) %>
                  <% else %>
                    <img src="https://bulma.io/images/placeholders/128x128.png">
                  <% end %>
                </p>
              </figure>

              <div class="media-content">
                <div class="content">
                  <strong><%= link_to friend.name, friend %></strong>, @<%= friend.username %>
                </div>
              </div>

              <div class="media-right">
                <% unless current_user.active_friends.include?(friend) || current_user.pending_friends.include?(friend) || current_user.received_friends.include?(friend) || current_user == friend %>
                  <%= link_to "Add Friend", user_friendships_path(user_id: current_user.id, friendship: {friend_id: friend}), method: :post, remote: true, class: "button is-link" %>
                <% end %>
              </div>
            </article>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/friendships/pending.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <%= render 'posts/profile' %>

      <div class="column is-two-thirds">
        <div class="box">
          <h1 class="title">Pending Requests for <%= @user.name %></h1><BR>
          
          <h2 class="subtitle">Received Requests</h2>

          <% if @received_requests.any? %>
            <% @received_requests.each do |friendship| %>
              <article class="media">
                <figure class="media-left">
                  <p class="image is-48x48">
                    <% if friendship.user.avatar.attached? %>
                      <%= image_tag friendship.user.avatar.variant(resize_to_fill: [128, 128, { gravity: 'Center' }]) %>
                    <% else %>
                      <img src="https://bulma.io/images/placeholders/128x128.png">
                    <% end %>
                  </p>
                </figure>

                <div class="media-content">
                  <div class="content">
                    <strong><%= link_to friendship.user.name, user_path(friendship.user) %></strong>, @<%= friendship.user.username %>
                  </div>
                </div>

                <div class="media-right">
                  <%= link_to "Accept Request", accept_friendship_path(user_id: current_user.id, friendship: {friend_id: friendship.user}), method: :post, remote: true, class: "button is-link" %>
                </div>
              </article>
            <% end %>
            <BR>
          <% else %>
            <div class="content"><blockquote>None.</blockquote></div>
          <% end %>

          <h2 class="subtitle">Sent Requests</h2>

          <% if @sent_requests.any? %>
            <% @sent_requests.each do |friendship| %>
              <article class="media">
                <figure class="media-left">
                  <p class="image is-48x48">
                    <% if friendship.friend.avatar.attached? %>
                      <%= image_tag friendship.friend.avatar.variant(resize_to_fill: [128, 128, { gravity: 'Center' }]) %>
                    <% else %>
                      <img src="https://bulma.io/images/placeholders/128x128.png">
                    <% end %>
                  </p>
                </figure>

                <div class="media-content">
                  <div class="content">
                    <strong><%= link_to friendship.friend.name, user_path(friendship.friend) %></strong>, @<%= friendship.friend.username %>
                  </div>
                </div>

                <div class="media-right">
                  <%= link_to "Cancel Request", friendship_path(friendship), method: :delete, local: true, data: {confirm: "Really cancel request?"}, class: "button is-link" %>
                </div>
              </article>
            <% end %>
          <% else %>
            <div class="content"><blockquote>None.</blockquote></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>