config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  resources :posts do
    resources :comments, except: [:index, :show, :new]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show] do
    resources :friendships, except: [:show, :edit, :update], shallow: true
  end

  get 'users/:user_id/friendships/pending', to: 'friendships#pending', as: :pending_friendships
  post 'users/:user_id/friendships/pending', to: 'friendships#accept', as: :accept_friendship

  devise_scope :user do
    authenticated :user do
      root to: "posts#index", as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:edit, :update, :destroy, :show]
  before_action :check_if_friends, only: [:show]
  before_action :authorize, only: [:edit, :update, :destroy]
  
  def index
    @posts = Post.where(author: current_user).or(Post.where(author: current_user.active_friends)).order("created_at DESC")
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = current_user.comments.build
    @like = current_user.likes.build
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to post_path(@post), notice: 'Post succesfully created.'
    else
      render :new, alert: 'Please check your errors.'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post succesfully updated.'
    else
      render :edit, alert: 'Please check your errors.'
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_path, notice: 'Post succesfully deleted.'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:content)
    end

    def authorize
      unless current_user == @post.author
        redirect_to posts_path, alert: 'You cannot do that.'
      end
    end

    def check_if_friends
      unless current_user.active_friends.include?(@post.author) || current_user == @post.author
        redirect_to posts_path, alert: 'You cannot do that.'
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <% if comment.author.avatar.attached? %>
        <%= image_tag comment.author.avatar.variant(resize_to_fill: [128, 128, { gravity: 'Center' }]) %>
      <% else %>
        <img src="https://bulma.io/images/placeholders/128x128.png">
      <% end %>
    </p>
  </figure>

  <div class="media-content">
    <div class="content">
      <strong><%= link_to comment.author.name, user_path(comment.author) %></strong><BR>
      <p>Posted <%= distance_of_time_in_words(comment.created_at, Time.now) %> ago</p>
      <p><%= comment.body %></p>
    </div>
  </div>
</article>

app/views/posts/_feed.html.erb
<div class="column is-two-thirds">
  <article class="media box">
    <figure class="media-left">
      <p class="image is-64x64">
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar.variant(resize_to_fill: [128, 128, { gravity: 'Center' }]) %>
        <% else %>
          <img src="https://bulma.io/images/placeholders/128x128.png">
        <% end %>
      </p>
    </figure>
    <div class="media-content">
      <%= render 'form' %>
    </div>
  </article>

  <% @posts.each do |post| %>
    <div class="box">
      <article class="media">
        <figure class="media-left">
          <p class="image is-64x64">
            <% if post.author.avatar.attached? %>
              <%= image_tag post.author.avatar.variant(resize_to_fill: [128, 128, { gravity: 'Center' }]) %>
            <% else %>
              <img src="https://bulma.io/images/placeholders/128x128.png">
            <% end %>
          </p>
        </figure>

        <div class="media-content">
          <div class="content">
            <strong><%= link_to post.author.name, user_path(post.author) %></strong><BR>
            <p><%= post.content %></p>
          </div>

          <nav class="level is-mobile is-size-7">
            <div class="level-left">
                <p class="level-item">
                  <%= post.likes.count %> Likes
                </p>
                <p class="level-item">
                  <%= post.comments.count %> Comments
                </p>
                <%= link_to "Reply", post, class: "level-item" %>
            </div>

            <div class="level-right">              
                <%= link_to post, class: "level-item" do %>
                  <span class="icon is-small"><i class="fa fa-link" aria-hidden="true"></i></span>
                <% end %>
                <% if post.author == current_user %>
                  <%= link_to edit_post_path(post), class: "level-item" do %>
                    <span class="icon is-small"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                  <% end %>
                  <%= link_to post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" } do %>
                    <span class="icon is-small"><i class="fa fa-trash" aria-hidden="true"></i></span>
                  <% end %>
                <% end %>
            </div>
          </nav>
        </div>
      </article>
    </div>
  <% end %>

</div>

app/views/posts/_form.html.erb
<%= form_with model: @post do |f| %>
  <div class="field">
    <div class="control">
      <%= f.text_area :content, placeholder: "What's happening?", class: "textarea" %>
    </div>
  </div>
  <div class="field is-grouped is-grouped-right">
    <div class="control">
      <%= f.submit "Post", class: "button is-link" %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <% if @post.author.avatar.attached? %>
        <%= image_tag @post.author.avatar.variant(resize_to_fill: [128, 128, { gravity: 'Center' }]) %>
      <% else %>
        <img src="https://bulma.io/images/placeholders/128x128.png">
      <% end %>
    </p>
  </figure>

  <div class="media-content">
    <div class="content">
      <p class="title is-4"><%= link_to @post.author.name, user_path(@post.author) %></p>
      <p class="subtitle is-6"><%= distance_of_time_in_words(@post.created_at, Time.now) %> ago</p>
      <hr>
      <p><%= @post.content %></p>
      <hr>
    </div>

    <nav class="level is-mobile is-size-7">
      <div class="level-left">
      </div>
      <div class="level-right">
        <p class="level-item">
          <%= @post.likes.count %> Likes
        </p>
        <% if @post.likes.where(user: current_user).exists? %>
          <%= link_to "Unlike", post_like_path(@post), method: :delete, local: true, data: {confirm: "Really unlike?"}, class: "level-item"  %>
        <% else %>
          <%= link_to "Like", post_likes_path(@post, like: { user_id: current_user.id }), method: :post, remote: true, class: "level-item" %>
        <% end %>

        <% if @post.author == current_user %>
          <%= link_to edit_post_path(@post), class: "level-item" do %>
            <span class="icon is-small"><i class="fa fa-pencil" aria-hidden="true"></i></span>
           <% end %>
          <%= link_to @post, method: :delete, data: { confirm: "Are you sure you want to delete this tweeet?" } do %>
            <span class="icon is-small"><i class="fa fa-trash" aria-hidden="true"></i></span>
          <% end %>
        <% end %>
      </div>
    </nav>
  </div>
</article>

app/views/posts/_profile.html.erb
<div class="column is-one-quarter">
  <div class="card">
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure class="image is-48x48">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar.variant(resize_to_fill: [128, 128, { gravity: 'Center' }]) %>
            <% else %>
              <img src="https://bulma.io/images/placeholders/128x128.png">
            <% end %>
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-4"><%= current_user.name %></p>
          <p class="subtitle is-6">@<%= current_user.username %></p>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <%= link_to "Friends", user_friendships_path(current_user), class: "card-footer-item" %>
      <%= link_to "Pending", pending_friendships_path(current_user), class: "card-footer-item" %>
      <%= link_to "Edit", edit_user_registration_path, class: "card-footer-item" %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Post #<%= @post.id %></h1>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', posts_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/posts/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <%= render 'profile' %>
      <%= render 'feed' %>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">New Post</h1>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', posts_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/posts/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <%= render 'profile' %>
      <div class="column is-two-thirds">
      <div class="box">
        <h1 class="title">Viewing Post #<%= @post.id %><h1>
        <%= render 'post' %><BR>

        <h2 class="subtitle">Comments (<%= @post.comments.size %>)</h2>
        <%= render partial: 'posts/comment', collection: @post.comments %>

        <%= render partial: 'comments/form' %>
        </div>
      </div>
    </div>
  </div>
</section>