config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  resources :posts do
    resources :comments, except: [:index, :show, :new]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show] do
    resources :friendships, except: [:show, :edit, :update], shallow: true
  end

  get 'users/:user_id/friendships/pending', to: 'friendships#pending', as: :pending_friendships
  post 'users/:user_id/friendships/pending', to: 'friendships#accept', as: :accept_friendship

  devise_scope :user do
    authenticated :user do
      root to: "posts#index", as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odinbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-link" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <% if user_signed_in? %>
          <%= link_to "Odinbook", authenticated_root_path, class: "navbar-item is-white is-size-5" %>
        <% else %>
          <%= link_to "Odinbook", unauthenticated_root_path, class: "navbar-item is-white is-size-5" %>
        <% end %>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasic">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasic" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">            
              <% if user_signed_in? %>
                <p class="control">
                  <%= link_to "New Post", new_post_path, class: "button is-link is-inverted" %>
                </p>
                <% if !current_user.pending_received_friendships.empty? %>
                  <p class="control">
                    <%= link_to "Friend Requests (#{current_user.pending_received_friendships.count})", pending_friendships_path(current_user), class: "button is-danger" %>
                  </p>
                <% end %>
                <p class="control">
                  <%= link_to current_user.name, user_path(current_user), class: "button is-link" %>
                </p>
                <p class="control">
                  <%= link_to "All Users", users_path, class: "button is-link" %>
                </p>
                <p class="control">
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-link" %>
                </p>
              <% else %>
                <p class="control">
                  <%= link_to 'Sign In', new_user_session_path, class: "button is-link" %>
                </p>
                <p class="control">
                  <%= link_to 'Sign Up', new_user_registration_path, class: "button is-link" %>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>